import commands from '../data/commands.json';
import recipes from '../data/recipes.json';
import enchantments from '../data/enchantments.json';
import mobs from '../data/mobs.json';
import guides from '../data/guides.json';
import potions from '../data/potions.json';
import villagers from '../data/villagers.json';
import itemData from '../data/items.json';
import farms from '../data/farms.json';
import biomes from '../data/biomes.json';
import structures from '../data/structures.json';
import seeds from '../data/seeds.json';
import versions from '../data/versions.json';

export async function GET() {
  const items = [
    ...commands.map(c => ({ name: `${c.name} command`, kind: 'command', url: `/commands/${c.slug}/`, keywords: c.keywords })),
    ...recipes.map(r => ({ name: `${r.name} recipe`, kind: 'recipe', url: `/recipes/${r.slug}/`, keywords: r.keywords })),
    ...enchantments.map(e => ({ name: e.name, kind: 'enchantment', url: `/enchantments/${e.slug}/`, keywords: e.keywords })),
    ...mobs.map(m => ({ name: m.name, kind: 'mob', url: `/mobs/${m.slug}/`, keywords: m.keywords })),
    ...guides.map(g => ({ name: g.name, kind: 'guide', url: `/guides/${g.slug}/`, keywords: g.keywords })),
    ...potions.map(x => ({ name: x.name, kind: 'potion', url: `/potions/${x.slug}/`, keywords: x.keywords })),
    ...villagers.map(v => ({ name: `${v.name} villager trades`, kind: 'villager', url: `/villagers/${v.slug}/`, keywords: v.keywords })),
    ...itemData.map(i => ({ name: i.name, kind: 'item', url: `/items/${i.slug}/`, keywords: i.keywords })),
    ...farms.map(f => ({ name: f.name, kind: 'farm', url: `/farms/${f.slug}/`, keywords: f.keywords })),
    ...biomes.map(b => ({ name: `${b.name} biome`, kind: 'biome', url: `/biomes/${b.slug}/`, keywords: b.keywords })),
    ...structures.map(s => ({ name: s.name, kind: 'structure', url: `/structures/${s.slug}/`, keywords: s.keywords })),
    ...seeds.map(s => ({ name: s.name, kind: 'seed', url: `/seeds/${s.slug}/`, keywords: s.keywords })),
    ...versions.map(v => ({ name: v.name, kind: 'version', url: `/versions/${v.slug}/`, keywords: v.keywords })),
    { name: 'Nether Coordinate Calculator', kind: 'tool', url: '/tools/nether-calculator/', keywords: 'nether calculator coordinates convert portal 8:1' },
    { name: 'XP Calculator', kind: 'tool', url: '/tools/xp-calculator/', keywords: 'xp calculator levels experience points enchanting level 30' },
    { name: 'Ore Finder: Best Y Levels', kind: 'tool', url: '/tools/ore-finder/', keywords: 'ore distribution best y level diamond iron gold mining' },
    { name: 'How to Install Mods', kind: 'guide', url: '/mods/install-mods-java/', keywords: 'install mods fabric neoforge modrinth java loader mods folder' },
    { name: 'Essential Performance Mods', kind: 'guide', url: '/mods/essential-mods/', keywords: 'sodium lithium iris fabric api jei emi jade appleskin performance fps' },
    { name: 'Best Content Mods', kind: 'guide', url: '/mods/best-content-mods/', keywords: 'create mod botania twilight forest farmers delight terralith mekanism' },
    { name: 'Shaders Guide', kind: 'guide', url: '/mods/shaders/', keywords: 'shaders iris complementary bsl install vibrant visuals' },
    { name: 'Bedrock Add-ons', kind: 'guide', url: '/mods/bedrock-addons/', keywords: 'bedrock addons mcaddon marketplace console mobile' },
    { name: 'Minecraft Advancements Guide', kind: 'guide', url: '/advancements/', keywords: 'advancements achievements list all tabs java guide' },
    { name: 'How Did We Get Here? advancement', kind: 'advancement', url: '/advancements/how-did-we-get-here/', keywords: 'how did we get here all effects hidden challenge 27' },
    { name: 'Hidden in the Depths advancement', kind: 'advancement', url: '/advancements/hidden-in-the-depths/', keywords: 'ancient debris find netherite mining y15' },
    { name: 'Hot Tourist Destinations advancement', kind: 'advancement', url: '/advancements/hot-tourist-destinations/', keywords: 'nether biomes explore all basalt deltas warped forest' },
    { name: 'Cover Me in Debris advancement', kind: 'advancement', url: '/advancements/cover-me-in-debris/', keywords: 'netherite armor full suit upgrade smithing template' },
    { name: 'Hero of the Village advancement', kind: 'advancement', url: '/advancements/hero-of-the-village/', keywords: 'raid defend village bad omen hero discount' },
    { name: 'Sniper Duel advancement', kind: 'advancement', url: '/advancements/sniper-duel/', keywords: 'skeleton 50 meters arrow bow kill' },
    { name: 'Two by Two advancement', kind: 'advancement', url: '/advancements/two-by-two/', keywords: 'breed all animals list two by two' },
    { name: 'Serious Dedication advancement', kind: 'advancement', url: '/advancements/serious-dedication/', keywords: 'netherite hoe upgrade smithing' },
    { name: 'Free the End advancement', kind: 'advancement', url: '/advancements/free-the-end/', keywords: 'ender dragon kill end fight guide' },
    { name: "Sky's the Limit advancement", kind: 'advancement', url: '/advancements/sky-s-the-limit/', keywords: 'elytra find end city ship outer end' },
    { name: 'Zombie Doctor advancement', kind: 'advancement', url: '/advancements/zombie-doctor/', keywords: 'cure zombie villager weakness golden apple trade discount' },
    { name: 'Eye Spy advancement', kind: 'advancement', url: '/advancements/eye-spy/', keywords: 'eye of ender stronghold find throw end portal' },
    { name: 'Cover Me with Diamonds advancement', kind: 'advancement', url: '/advancements/cover-me-with-diamonds/', keywords: 'diamond armor craft mine y -59' },
    { name: 'Those Were the Days advancement', kind: 'advancement', url: '/advancements/those-were-the-days/', keywords: 'bastion remnant enter nether piglin gold armor' },
    { name: 'War Pigs advancement', kind: 'advancement', url: '/advancements/war-pigs/', keywords: 'bastion chest loot piglin brute treasure netherite template' },
    { name: 'Uneasy Alliance advancement', kind: 'advancement', url: '/advancements/uneasy-alliance/', keywords: 'ghast overworld portal lure fishing rod kill' },
    { name: 'Withering Heights advancement', kind: 'advancement', url: '/advancements/withering-heights/', keywords: 'summon wither skulls soul sand farm looting' },
    { name: 'Beaconator advancement', kind: 'advancement', url: '/advancements/beaconator/', keywords: 'beacon full power pyramid 164 blocks nether star' },
    { name: 'A Furious Cocktail advancement', kind: 'advancement', url: '/advancements/a-furious-cocktail/', keywords: 'all potion effects 17 turtle master splash' },
    { name: 'The Next Generation advancement', kind: 'advancement', url: '/advancements/the-next-generation/', keywords: 'dragon egg collect torch piston trophy' },
    { name: 'You Need a Mint advancement', kind: 'advancement', url: '/advancements/you-need-a-mint/', keywords: 'dragons breath bottle lingering potion collect' },
    { name: 'The City at the End of the Game advancement', kind: 'advancement', url: '/advancements/the-city-at-the-end-of-the-game/', keywords: 'end city gateway pearl outer islands' },
    { name: 'Voluntary Exile advancement', kind: 'advancement', url: '/advancements/voluntary-exile/', keywords: 'raid captain kill ominous bottle bad omen hidden' },
    { name: 'Monsters Hunted advancement', kind: 'advancement', url: '/advancements/monsters-hunted/', keywords: 'kill every hostile monster 41 warden breeze list' },
    { name: 'Adventuring Time advancement', kind: 'advancement', url: '/advancements/adventuring-time/', keywords: 'visit every biome 56 explore elytra 500 xp' },
    { name: 'Postmortal advancement', kind: 'advancement', url: '/advancements/postmortal/', keywords: 'totem of undying evoker cheat death use' },
    { name: 'Very Very Frightening advancement', kind: 'advancement', url: '/advancements/very-very-frightening/', keywords: 'lightning villager channeling trident thunderstorm witch' },
    { name: 'Bullseye advancement', kind: 'advancement', url: '/advancements/bullseye/', keywords: 'target block bullseye 30 blocks arrow redstone' },
    { name: 'A Complete Catalogue advancement', kind: 'advancement', url: '/advancements/a-complete-catalogue/', keywords: 'tame all cat variants 11 village swamp hut' },
    { name: 'Best Friends Forever advancement', kind: 'advancement', url: '/advancements/best-friends-forever/', keywords: 'tame animal wolf bones cat fish' },
    { name: 'A Balanced Diet advancement', kind: 'advancement', url: '/advancements/a-balanced-diet/', keywords: 'eat every food 40 suspicious stew pufferfish' },
    { name: 'Suit Up advancement', kind: 'advancement', url: '/advancements/suit-up/', keywords: 'iron armor craft get suit up story' },
    { name: 'Ice Bucket Challenge advancement', kind: 'advancement', url: '/advancements/ice-bucket-challenge/', keywords: 'obsidian get mine diamond pickaxe lava water' },
    { name: 'Enchanter advancement', kind: 'advancement', url: '/advancements/enchanter/', keywords: 'enchanting table craft use lapis bookshelves' },
    { name: 'A Terrible Fortress advancement', kind: 'advancement', url: '/advancements/a-terrible-fortress/', keywords: 'find nether fortress where spawn basalt deltas region' },
    { name: 'Return to Sender advancement', kind: 'advancement', url: '/advancements/return-to-sender/', keywords: 'ghast fireball deflect reflect kill 50 xp' },
    { name: 'Oh Shiny advancement', kind: 'advancement', url: '/advancements/oh-shiny/', keywords: 'piglin distract gold bartering angry armor' },
    { name: 'Into Fire advancement', kind: 'advancement', url: '/advancements/into-fire/', keywords: 'blaze rod get blaze fortress looting drop' },
    { name: 'Local Brewery advancement', kind: 'advancement', url: '/advancements/local-brewery/', keywords: 'brewing stand craft potion water bottle nether wart' },
    { name: 'Great View From Up Here advancement', kind: 'advancement', url: '/advancements/great-view-from-up-here/', keywords: 'shulker levitation 50 blocks end city float' },
    { name: "Ol' Betsy advancement", kind: 'advancement', url: '/advancements/ol-betsy/', keywords: 'crossbow shoot craft pillager quick charge multishot' },
    { name: 'Diamonds! advancement', kind: 'advancement', url: '/advancements/diamonds/', keywords: 'find diamonds y level -59 deepslate iron pickaxe' },
    { name: 'We Need to Go Deeper advancement', kind: 'advancement', url: '/advancements/we-need-to-go-deeper/', keywords: 'nether portal build light obsidian flint steel' },
    { name: 'Spooky Scary Skeleton advancement', kind: 'advancement', url: '/advancements/spooky-scary-skeleton/', keywords: 'wither skeleton skull drop chance looting farm fortress' },
    { name: 'Subspace Bubble advancement', kind: 'advancement', url: '/advancements/subspace-bubble/', keywords: 'nether travel 7000 blocks 875 fast travel portal' },
    { name: 'Who is Cutting Onions? advancement', kind: 'advancement', url: '/advancements/who-is-cutting-onions/', keywords: 'crying obsidian get bartering ruined portal respawn anchor' },
    { name: 'This Boat Has Legs advancement', kind: 'advancement', url: '/advancements/this-boat-has-legs/', keywords: 'ride strider warped fungus stick saddle lava' },
    { name: 'Feels Like Home advancement', kind: 'advancement', url: '/advancements/feels-like-home/', keywords: 'strider overworld lava 50 blocks ride lake' },
    { name: 'Bring Home the Beacon advancement', kind: 'advancement', url: '/advancements/bring-home-the-beacon/', keywords: 'beacon craft pyramid mineral blocks nether star wither' },
    { name: 'Sticky Situation advancement', kind: 'advancement', url: '/advancements/sticky-situation/', keywords: 'honey block fall slide side break fall' },
    { name: 'Caves & Cliffs advancement', kind: 'advancement', url: '/advancements/caves-cliffs/', keywords: 'fall world height 319 -59 survive water bucket' },
    { name: 'Acquire Hardware advancement', kind: 'advancement', url: '/advancements/acquire-hardware/', keywords: 'iron ingot smelt raw iron furnace blast' },
    { name: 'Hot Stuff advancement', kind: 'advancement', url: '/advancements/hot-stuff/', keywords: 'lava bucket fill source block fuel' },
    { name: 'Not Today, Thank You advancement', kind: 'advancement', url: '/advancements/not-today-thank-you/', keywords: 'shield craft block projectile skeleton arrow' },
    { name: 'Sweet Dreams advancement', kind: 'advancement', url: '/advancements/sweet-dreams/', keywords: 'bed craft sleep respawn point wool planks' },
    { name: 'Hired Help advancement', kind: 'advancement', url: '/advancements/hired-help/', keywords: 'iron golem build summon iron blocks carved pumpkin' },
    { name: 'Bee Our Guest advancement', kind: 'advancement', url: '/advancements/bee-our-guest/', keywords: 'honey bottle campfire beehive nest harvest calm bees' },
    { name: 'The End... Again... advancement', kind: 'advancement', url: '/advancements/the-end-again/', keywords: 'respawn ender dragon end crystals exit portal gateway' },
    { name: 'Heart Transplanter advancement', kind: 'advancement', url: '/advancements/heart-transplanter/', keywords: 'creaking heart silk touch pale oak logs pale garden align' },
    { name: 'What a Deal! advancement', kind: 'advancement', url: '/advancements/what-a-deal/', keywords: 'trade villager emeralds wandering trader output' },
    { name: 'Tactical Fishing advancement', kind: 'advancement', url: '/advancements/tactical-fishing/', keywords: 'fish bucket water catch cod salmon tropical pufferfish' },
    { name: 'Not Quite "Nine" Lives advancement', kind: 'advancement', url: '/advancements/not-quite-nine-lives/', keywords: 'respawn anchor charge glowstone nether max 4' },
    { name: 'The End? advancement', kind: 'advancement', url: '/advancements/the-end-minecraft/', keywords: 'enter end portal stronghold eyes of ender fill frames' },
    { name: 'Remote Getaway advancement', kind: 'advancement', url: '/advancements/remote-getaway/', keywords: 'end gateway ender pearl escape island outer end' },
    { name: 'Take Aim advancement', kind: 'advancement', url: '/advancements/take-aim/', keywords: 'bow craft arrows shoot mob crossbow' },
    { name: 'Fishy Business advancement', kind: 'advancement', url: '/advancements/fishy-business/', keywords: 'fishing rod craft catch cod salmon bobber reel' },
    { name: 'The Parrots and the Bats advancement', kind: 'advancement', url: '/advancements/the-parrots-and-the-bats/', keywords: 'breed animals two wheat carrots seeds baby' },
    { name: 'Total Beelocation advancement', kind: 'advancement', url: '/advancements/total-beelocation/', keywords: 'silk touch bee nest 3 bees move relocate' },
    { name: "Isn't It Scute? advancement", kind: 'advancement', url: '/advancements/isn-t-it-scute/', keywords: 'armadillo scute brush wolf armor savanna' },
    { name: 'Minecraft: Trial(s) Edition advancement', kind: 'advancement', url: '/advancements/minecraft-trial-s-edition/', keywords: 'trial chambers find cartographer explorer map enter' },
    { name: 'Surge Protector advancement', kind: 'advancement', url: '/advancements/surge-protector/', keywords: 'lightning rod villager thunderstorm strike no fire' },
    { name: 'Stone Age advancement', kind: 'advancement', url: '/advancements/stone-age/', keywords: 'mine stone cobblestone wooden pickaxe first' },
    { name: 'Monster Hunter advancement', kind: 'advancement', url: '/advancements/monster-hunter/', keywords: 'kill hostile monster zombie skeleton spider sword' },
    { name: 'Country Lode, Take Me Home advancement', kind: 'advancement', url: '/advancements/country-lode-take-me-home/', keywords: 'lodestone compass waypoint netherite bastion' },
    { name: 'Crafting a New Look advancement', kind: 'advancement', url: '/advancements/crafting-a-new-look/', keywords: 'armor trim smithing table template duplicate diamonds' },
    { name: 'Under Lock and Key advancement', kind: 'advancement', url: '/advancements/under-lock-and-key/', keywords: 'trial key vault unlock trial chambers loot' },
    { name: 'Smells Interesting advancement', kind: 'advancement', url: '/advancements/smells-interesting/', keywords: 'sniffer egg brush suspicious sand ocean ruins hidden' },
    { name: 'The Cutest Predator advancement', kind: 'advancement', url: '/advancements/the-cutest-predator/', keywords: 'axolotl bucket lush caves catch blue rare' },
    { name: 'Wax On advancement', kind: 'advancement', url: '/advancements/wax-on/', keywords: 'honeycomb copper block wax oxidation stop' },
    { name: 'Stay Hydrated! advancement', kind: 'advancement', url: '/advancements/stay-hydrated/', keywords: 'dried ghast water place rehydrate ghastling happy' },
    { name: 'Uh Oh advancement', kind: 'advancement', url: '/advancements/uh-oh/', keywords: 'sulfur cube absorb tnt feed explosive archetype' },
    { name: 'How to Beat the Ender Dragon in Minecraft', kind: 'guide', url: '/guides/how-to-beat-ender-dragon/', keywords: 'ender dragon kill beat boss end crystals perch bed explode respawn' },
    { name: 'How to Cure a Zombie Villager in Minecraft', kind: 'guide', url: '/guides/how-to-cure-zombie-villager/', keywords: 'cure zombie villager weakness splash potion golden apple discount trading' },
    { name: 'How to Find a Stronghold in Minecraft', kind: 'guide', url: '/guides/how-to-find-stronghold/', keywords: 'find stronghold eye of ender end portal triangulate silverfish spawner 128' },
    { name: 'How to Fly with Elytra in Minecraft', kind: 'guide', url: '/guides/how-to-fly-elytra/', keywords: 'elytra fly glide fireworks boost rocket mending phantom membrane takeoff' },
    { name: 'How to Find and Beat Trial Chambers in Minecraft', kind: 'guide', url: '/guides/how-to-find-trial-chambers/', keywords: 'trial chambers find map cartographer vault ominous key heavy core mace breeze' },
    { name: 'How to Get Mending in Minecraft', kind: 'guide', url: '/guides/how-to-get-mending/', keywords: 'mending enchantment librarian lectern reroll treasure swamp trade rebalance book' },
    { name: 'How to Make a Minecraft Server', kind: 'guide', url: '/servers/make-a-server/', keywords: 'make server paper port forwarding 25565 playit whitelist eula' },
    { name: 'Free Server Hosting', kind: 'guide', url: '/servers/free-hosting/', keywords: 'aternos free hosting minecraft server java bedrock' },
    { name: 'Essential Server Plugins', kind: 'guide', url: '/servers/plugins/', keywords: 'luckperms essentialsx geysermc viaversion coreprotect plugins paper' }
  ];
  return new Response(JSON.stringify(items), { headers: { 'Content-Type': 'application/json' } });
}
