import commands from '../data/commands.json';
import recipes from '../data/recipes.json';
import enchantments from '../data/enchantments.json';
import mobs from '../data/mobs.json';
import guides from '../data/guides.json';
import guidesEs from '../data/guides-es.json';
import potions from '../data/potions.json';
import villagers from '../data/villagers.json';
import itemData from '../data/items.json';
import farms from '../data/farms.json';
import biomes from '../data/biomes.json';
import structures from '../data/structures.json';
import seeds from '../data/seeds.json';
import versions from '../data/versions.json';

export async function GET() {
  const items = [
    ...commands.map(c => ({ name: `${c.name} comando`, kind: 'comando', url: `/es/commands/${c.slug}/`, keywords: `${c.keywords} comando` })),
    ...recipes.map(r => ({ name: `${r.name} receta`, kind: 'receta', url: `/es/recipes/${r.slug}/`, keywords: `${r.keywords} receta crafteo` })),
    ...enchantments.map(e => ({ name: e.name, kind: 'encantamiento', url: `/es/enchantments/${e.slug}/`, keywords: `${e.keywords} encantamiento` })),
    ...mobs.map(m => ({ name: m.name, kind: 'mob', url: `/es/mobs/${m.slug}/`, keywords: m.keywords })),
    ...guides.map(g => ({ name: (guidesEs as any)[g.slug]?.name ?? g.name, kind: 'guía', url: `/es/guides/${g.slug}/`, keywords: `${g.keywords} guía` })),
    ...potions.map(x => ({ name: x.name, kind: 'poción', url: `/es/potions/${x.slug}/`, keywords: `${x.keywords} poción` })),
    ...villagers.map(v => ({ name: `Comercio de ${v.name}`, kind: 'aldeano', url: `/es/villagers/${v.slug}/`, keywords: `${v.keywords} aldeano comercio trades` })),
    ...itemData.map(i => ({ name: i.name, kind: 'objeto', url: `/es/items/${i.slug}/`, keywords: `${i.keywords} objeto` })),
    ...farms.map(f => ({ name: f.name, kind: 'granja', url: `/es/farms/${f.slug}/`, keywords: `${f.keywords} granja` })),
    ...biomes.map(b => ({ name: `${b.name} bioma`, kind: 'bioma', url: `/es/biomes/${b.slug}/`, keywords: `${b.keywords} bioma` })),
    ...structures.map(s => ({ name: s.name, kind: 'estructura', url: `/es/structures/${s.slug}/`, keywords: `${s.keywords} estructura` })),
    ...seeds.map(s => ({ name: s.name, kind: 'semilla', url: `/es/seeds/${s.slug}/`, keywords: `${s.keywords} semilla` })),
    ...versions.map(v => ({ name: v.name, kind: 'versión', url: `/es/versions/${v.slug}/`, keywords: `${v.keywords} versión actualización` })),
    { name: 'Calculadora de coordenadas del Nether', kind: 'herramienta', url: '/es/tools/nether-calculator/', keywords: 'nether calculadora coordenadas convertir portal 8:1 calculator' },
    { name: 'Calculadora de XP', kind: 'herramienta', url: '/es/tools/xp-calculator/', keywords: 'xp calculadora niveles experiencia puntos encantar nivel 30 calculator' },
    { name: 'Ore Finder: mejores niveles Y', kind: 'herramienta', url: '/es/tools/ore-finder/', keywords: 'minerales distribución mejor nivel y diamante hierro oro minar ore finder' },
    { name: 'Cómo instalar mods (Java)', kind: 'guía', url: '/es/mods/install-mods-java/', keywords: 'instalar mods fabric neoforge modrinth java loader carpeta mods install' },
    { name: 'Mods esenciales de rendimiento y QoL', kind: 'guía', url: '/es/mods/essential-mods/', keywords: 'sodium lithium iris fabric api jei emi jade appleskin rendimiento fps mods esenciales' },
    { name: 'Los mejores mods de contenido', kind: 'guía', url: '/es/mods/best-content-mods/', keywords: 'create mod botania twilight forest farmers delight terralith mekanism mods contenido' },
    { name: 'Guía de shaders', kind: 'guía', url: '/es/mods/shaders/', keywords: 'shaders iris complementary bsl instalar vibrant visuals' },
    { name: 'Add-ons de Bedrock', kind: 'guía', url: '/es/mods/bedrock-addons/', keywords: 'bedrock addons mcaddon marketplace consola móvil' },
    { name: 'Guía de advancements de Minecraft', kind: 'guía', url: '/es/advancements/', keywords: 'advancements logros lista todas las pestañas java guía' },
    { name: 'How Did We Get Here? (advancement)', kind: 'advancement', url: '/es/advancements/how-did-we-get-here/', keywords: 'how did we get here todos los efectos desafío oculto 27' },
    { name: 'Hidden in the Depths (advancement)', kind: 'advancement', url: '/es/advancements/hidden-in-the-depths/', keywords: 'ancient debris encontrar netherite minar y15' },
    { name: 'Hot Tourist Destinations (advancement)', kind: 'advancement', url: '/es/advancements/hot-tourist-destinations/', keywords: 'biomas nether explorar todos basalt deltas warped forest' },
    { name: 'Cover Me in Debris (advancement)', kind: 'advancement', url: '/es/advancements/cover-me-in-debris/', keywords: 'armadura netherite completa mejora smithing template' },
    { name: 'Hero of the Village (advancement)', kind: 'advancement', url: '/es/advancements/hero-of-the-village/', keywords: 'raid incursión defender aldea bad omen héroe descuento' },
    { name: 'Sniper Duel (advancement)', kind: 'advancement', url: '/es/advancements/sniper-duel/', keywords: 'skeleton 50 metros flecha arco matar' },
    { name: 'Two by Two (advancement)', kind: 'advancement', url: '/es/advancements/two-by-two/', keywords: 'criar todos los animales lista' },
    { name: 'Serious Dedication (advancement)', kind: 'advancement', url: '/es/advancements/serious-dedication/', keywords: 'azada netherite mejora smithing' },
    { name: 'Free the End (advancement)', kind: 'advancement', url: '/es/advancements/free-the-end/', keywords: 'ender dragon matar end combate guía' },
    { name: "Sky's the Limit (advancement)", kind: 'advancement', url: '/es/advancements/sky-s-the-limit/', keywords: 'elytra encontrar end city barco end exterior' },
    { name: 'Zombie Doctor (advancement)', kind: 'advancement', url: '/es/advancements/zombie-doctor/', keywords: 'cure zombie villager weakness golden apple trade discount' },
    { name: 'Eye Spy (advancement)', kind: 'advancement', url: '/es/advancements/eye-spy/', keywords: 'eye of ender stronghold find throw end portal' },
    { name: 'Cover Me with Diamonds (advancement)', kind: 'advancement', url: '/es/advancements/cover-me-with-diamonds/', keywords: 'diamond armor craft mine y -59' },
    { name: 'Those Were the Days (advancement)', kind: 'advancement', url: '/es/advancements/those-were-the-days/', keywords: 'bastion remnant enter nether piglin gold armor' },
    { name: 'War Pigs (advancement)', kind: 'advancement', url: '/es/advancements/war-pigs/', keywords: 'bastion chest loot piglin brute treasure netherite template' },
    { name: 'Uneasy Alliance (advancement)', kind: 'advancement', url: '/es/advancements/uneasy-alliance/', keywords: 'ghast overworld portal lure fishing rod kill' },
    { name: 'Withering Heights (advancement)', kind: 'advancement', url: '/es/advancements/withering-heights/', keywords: 'summon wither skulls soul sand farm looting' },
    { name: 'Beaconator (advancement)', kind: 'advancement', url: '/es/advancements/beaconator/', keywords: 'beacon full power pyramid 164 blocks nether star' },
    { name: 'A Furious Cocktail (advancement)', kind: 'advancement', url: '/es/advancements/a-furious-cocktail/', keywords: 'all potion effects 17 turtle master splash' },
    { name: 'The Next Generation (advancement)', kind: 'advancement', url: '/es/advancements/the-next-generation/', keywords: 'dragon egg collect torch piston trophy' },
    { name: 'You Need a Mint (advancement)', kind: 'advancement', url: '/es/advancements/you-need-a-mint/', keywords: 'dragons breath bottle lingering potion collect' },
    { name: 'The City at the End of the Game (advancement)', kind: 'advancement', url: '/es/advancements/the-city-at-the-end-of-the-game/', keywords: 'end city gateway pearl outer islands' },
    { name: 'Voluntary Exile (advancement)', kind: 'advancement', url: '/es/advancements/voluntary-exile/', keywords: 'raid captain kill ominous bottle bad omen hidden' },
    { name: 'Monsters Hunted (advancement)', kind: 'advancement', url: '/es/advancements/monsters-hunted/', keywords: 'kill every hostile monster 41 warden breeze list' },
    { name: 'Adventuring Time (advancement)', kind: 'advancement', url: '/es/advancements/adventuring-time/', keywords: 'visit every biome 56 explore elytra 500 xp' },
    { name: 'Postmortal (advancement)', kind: 'advancement', url: '/es/advancements/postmortal/', keywords: 'totem of undying evoker cheat death use' },
    { name: 'Very Very Frightening (advancement)', kind: 'advancement', url: '/es/advancements/very-very-frightening/', keywords: 'lightning villager channeling trident thunderstorm witch' },
    { name: 'Bullseye (advancement)', kind: 'advancement', url: '/es/advancements/bullseye/', keywords: 'target block bullseye 30 blocks arrow redstone' },
    { name: 'A Complete Catalogue (advancement)', kind: 'advancement', url: '/es/advancements/a-complete-catalogue/', keywords: 'tame all cat variants 11 village swamp hut' },
    { name: 'Best Friends Forever (advancement)', kind: 'advancement', url: '/es/advancements/best-friends-forever/', keywords: 'tame animal wolf bones cat fish' },
    { name: 'A Balanced Diet (advancement)', kind: 'advancement', url: '/es/advancements/a-balanced-diet/', keywords: 'eat every food 40 suspicious stew pufferfish' },
    { name: 'Suit Up (advancement)', kind: 'advancement', url: '/es/advancements/suit-up/', keywords: 'armadura hierro fabricar conseguir suit up' },
    { name: 'Ice Bucket Challenge (advancement)', kind: 'advancement', url: '/es/advancements/ice-bucket-challenge/', keywords: 'obsidiana conseguir picar pico diamante lava agua' },
    { name: 'Enchanter (advancement)', kind: 'advancement', url: '/es/advancements/enchanter/', keywords: 'mesa encantamientos fabricar usar lapislazuli librerias' },
    { name: 'A Terrible Fortress (advancement)', kind: 'advancement', url: '/es/advancements/a-terrible-fortress/', keywords: 'encontrar fortaleza nether donde aparece basalt deltas' },
    { name: 'Return to Sender (advancement)', kind: 'advancement', url: '/es/advancements/return-to-sender/', keywords: 'ghast bola fuego devolver reflejar matar 50 xp' },
    { name: 'Oh Shiny (advancement)', kind: 'advancement', url: '/es/advancements/oh-shiny/', keywords: 'piglin distraer oro trueque enfadado armadura' },
    { name: 'Into Fire (advancement)', kind: 'advancement', url: '/es/advancements/into-fire/', keywords: 'blaze rod conseguir blaze fortaleza saqueo drop' },
    { name: 'Local Brewery (advancement)', kind: 'advancement', url: '/es/advancements/local-brewery/', keywords: 'brewing stand fabricar pocion botella agua nether wart' },
    { name: 'Great View From Up Here (advancement)', kind: 'advancement', url: '/es/advancements/great-view-from-up-here/', keywords: 'shulker levitacion 50 bloques end city flotar' },
    { name: "Ol' Betsy (advancement)", kind: 'advancement', url: '/es/advancements/ol-betsy/', keywords: 'ballesta disparar fabricar pillager carga rapida multidisparo' },
    { name: 'Diamonds! (advancement)', kind: 'advancement', url: '/es/advancements/diamonds/', keywords: 'encontrar diamantes nivel y -59 deepslate pico hierro' },
    { name: 'We Need to Go Deeper (advancement)', kind: 'advancement', url: '/es/advancements/we-need-to-go-deeper/', keywords: 'portal nether construir encender obsidiana mechero' },
    { name: 'Spooky Scary Skeleton (advancement)', kind: 'advancement', url: '/es/advancements/spooky-scary-skeleton/', keywords: 'calavera wither skeleton probabilidad saqueo granja fortaleza' },
    { name: 'Subspace Bubble (advancement)', kind: 'advancement', url: '/es/advancements/subspace-bubble/', keywords: 'viaje nether 7000 bloques 875 viaje rapido portal' },
    { name: 'Who is Cutting Onions? (advancement)', kind: 'advancement', url: '/es/advancements/who-is-cutting-onions/', keywords: 'crying obsidian conseguir trueque ruined portal respawn anchor' },
    { name: 'This Boat Has Legs (advancement)', kind: 'advancement', url: '/es/advancements/this-boat-has-legs/', keywords: 'montar strider hongo warped palo montura lava' },
    { name: 'Feels Like Home (advancement)', kind: 'advancement', url: '/es/advancements/feels-like-home/', keywords: 'strider overworld lava 50 bloques cabalgar lago' },
    { name: 'Bring Home the Beacon (advancement)', kind: 'advancement', url: '/es/advancements/bring-home-the-beacon/', keywords: 'beacon fabricar piramide bloques minerales nether star wither' },
    { name: 'Sticky Situation (advancement)', kind: 'advancement', url: '/es/advancements/sticky-situation/', keywords: 'bloque miel caida deslizar lateral amortiguar' },
    { name: 'Caves & Cliffs (advancement)', kind: 'advancement', url: '/es/advancements/caves-cliffs/', keywords: 'caida altura mundo 319 -59 sobrevivir cubo agua' },
    { name: 'Acquire Hardware (advancement)', kind: 'advancement', url: '/es/advancements/acquire-hardware/', keywords: 'lingote hierro fundir horno alto horno' },
    { name: 'Hot Stuff (advancement)', kind: 'advancement', url: '/es/advancements/hot-stuff/', keywords: 'cubo lava rellenar bloque fuente combustible' },
    { name: 'Not Today, Thank You (advancement)', kind: 'advancement', url: '/es/advancements/not-today-thank-you/', keywords: 'escudo fabricar bloquear proyectil esqueleto flecha' },
    { name: 'Sweet Dreams (advancement)', kind: 'advancement', url: '/es/advancements/sweet-dreams/', keywords: 'cama fabricar dormir punto respawn lana tablones' },
    { name: 'Hired Help (advancement)', kind: 'advancement', url: '/es/advancements/hired-help/', keywords: 'iron golem construir invocar bloques hierro calabaza tallada' },
    { name: 'Bee Our Guest (advancement)', kind: 'advancement', url: '/es/advancements/bee-our-guest/', keywords: 'botella miel hoguera colmena nido cosechar abejas tranquilas' },
    { name: 'The End... Again... (advancement)', kind: 'advancement', url: '/es/advancements/the-end-again/', keywords: 'reinvocar ender dragon end crystals portal salida gateway' },
    { name: 'Heart Transplanter (advancement)', kind: 'advancement', url: '/es/advancements/heart-transplanter/', keywords: 'creaking heart toque seda pale oak logs pale garden alinear' },
    { name: 'What a Deal! (advancement)', kind: 'advancement', url: '/es/advancements/what-a-deal/', keywords: 'trueque aldeano esmeraldas wandering trader' },
    { name: 'Tactical Fishing (advancement)', kind: 'advancement', url: '/es/advancements/tactical-fishing/', keywords: 'cubo pez agua pescar cod salmon tropical pufferfish' },
    { name: 'Not Quite "Nine" Lives (advancement)', kind: 'advancement', url: '/es/advancements/not-quite-nine-lives/', keywords: 'respawn anchor cargar glowstone nether maximo 4' },
    { name: 'The End? (advancement)', kind: 'advancement', url: '/es/advancements/the-end-minecraft/', keywords: 'entrar end portal stronghold ojos ender rellenar marcos' },
    { name: 'Remote Getaway (advancement)', kind: 'advancement', url: '/es/advancements/remote-getaway/', keywords: 'end gateway ender pearl escapar isla end exterior' },
    { name: 'Take Aim (advancement)', kind: 'advancement', url: '/es/advancements/take-aim/', keywords: 'arco fabricar flechas disparar mob ballesta' },
    { name: 'Fishy Business (advancement)', kind: 'advancement', url: '/es/advancements/fishy-business/', keywords: 'cana pescar fabricar pescar corcho recoger' },
    { name: 'The Parrots and the Bats (advancement)', kind: 'advancement', url: '/es/advancements/the-parrots-and-the-bats/', keywords: 'criar animales dos trigo zanahorias semillas cria' },
    { name: 'Total Beelocation (advancement)', kind: 'advancement', url: '/es/advancements/total-beelocation/', keywords: 'toque seda nido abejas 3 mudar trasladar' },
    { name: "Isn't It Scute? (advancement)", kind: 'advancement', url: '/es/advancements/isn-t-it-scute/', keywords: 'armadillo scute cepillo armadura lobo sabana' },
    { name: 'Minecraft: Trial(s) Edition (advancement)', kind: 'advancement', url: '/es/advancements/minecraft-trial-s-edition/', keywords: 'trial chambers encontrar cartografo mapa explorador entrar' },
    { name: 'Surge Protector (advancement)', kind: 'advancement', url: '/es/advancements/surge-protector/', keywords: 'pararrayos aldeano tormenta rayo sin fuego' },
    { name: 'Stone Age (advancement)', kind: 'advancement', url: '/es/advancements/stone-age/', keywords: 'picar piedra cobblestone pico madera primero' },
    { name: 'Monster Hunter (advancement)', kind: 'advancement', url: '/es/advancements/monster-hunter/', keywords: 'matar monstruo hostil zombi esqueleto arana espada' },
    { name: 'Country Lode, Take Me Home (advancement)', kind: 'advancement', url: '/es/advancements/country-lode-take-me-home/', keywords: 'lodestone brujula imantada netherite bastion' },
    { name: 'Crafting a New Look (advancement)', kind: 'advancement', url: '/es/advancements/crafting-a-new-look/', keywords: 'armor trim smithing table template duplicar diamantes' },
    { name: 'Under Lock and Key (advancement)', kind: 'advancement', url: '/es/advancements/under-lock-and-key/', keywords: 'trial key vault abrir trial chambers botin' },
    { name: 'Smells Interesting (advancement)', kind: 'advancement', url: '/es/advancements/smells-interesting/', keywords: 'sniffer egg cepillo suspicious sand ruinas oceanicas oculto' },
    { name: 'The Cutest Predator (advancement)', kind: 'advancement', url: '/es/advancements/the-cutest-predator/', keywords: 'axolotl cubo lush caves atrapar azul raro' },
    { name: 'Wax On (advancement)', kind: 'advancement', url: '/es/advancements/wax-on/', keywords: 'panal cobre encerar oxidacion parar' },
    { name: 'Stay Hydrated! (advancement)', kind: 'advancement', url: '/es/advancements/stay-hydrated/', keywords: 'dried ghast agua colocar rehidratar ghastling happy' },
    { name: 'Uh Oh (advancement)', kind: 'advancement', url: '/es/advancements/uh-oh/', keywords: 'sulfur cube absorber tnt alimentar explosivo arquetipo' },
    { name: 'Getting an Upgrade (advancement)', kind: 'advancement', url: '/es/advancements/getting-an-upgrade/', keywords: 'pico piedra fabricar cobblestone mejorar madera' },
    { name: 'Sneak 100 (advancement)', kind: 'advancement', url: '/es/advancements/sneak-100/', keywords: 'sigilo sculk sensor warden agacharse 8 bloques deep dark' },
    { name: 'Respecting the Remnants (advancement)', kind: 'advancement', url: '/es/advancements/respecting-the-remnants/', keywords: 'cepillo suspicious sand gravel pottery sherd arqueologia' },
    { name: 'Sound of Music (advancement)', kind: 'advancement', url: '/es/advancements/sound-of-music/', keywords: 'jukebox meadow disco musica montana' },
    { name: 'Who Needs Rockets? (advancement)', kind: 'advancement', url: '/es/advancements/who-needs-rockets/', keywords: 'wind charge lanzar 8 bloques salto pies' },
    { name: 'Over-Overkill (advancement)', kind: 'advancement', url: '/es/advancements/over-overkill/', keywords: 'mace 50 corazones daño golpe density caida' },
    { name: 'Revaulting (advancement)', kind: 'advancement', url: '/es/advancements/revaulting/', keywords: 'ominous trial key vault bad omen spawner abrir' },
    { name: 'It Spreads (advancement)', kind: 'advancement', url: '/es/advancements/it-spreads/', keywords: 'sculk catalyst matar mob cerca experiencia deep dark' },
    { name: 'With Our Powers Combined! (advancement)', kind: 'advancement', url: '/es/advancements/with-our-powers-combined/', keywords: 'todos froglights ochre pearlescent verdant rana magma cube' },
    { name: 'The Healing Power of Friendship! (advancement)', kind: 'advancement', url: '/es/advancements/the-healing-power-of-friendship/', keywords: 'axolotl regeneracion pelea ayuda fatiga mineria' },
    { name: 'Cómo derrotar al ender dragon en Minecraft', kind: 'guía', url: '/es/guides/how-to-beat-ender-dragon/', keywords: 'ender dragon matar derrotar jefe end crystals posar cama explotar resucitar' },
    { name: 'Cómo curar a un aldeano zombi en Minecraft', kind: 'guía', url: '/es/guides/how-to-cure-zombie-villager/', keywords: 'curar aldeano zombi debilidad poción arrojadiza manzana dorada descuento trueques' },
    { name: 'Cómo encontrar una stronghold en Minecraft', kind: 'guía', url: '/es/guides/how-to-find-stronghold/', keywords: 'encontrar stronghold ojo de ender portal end triangular silverfish spawner' },
    { name: 'Cómo volar con elytra en Minecraft', kind: 'guía', url: '/es/guides/how-to-fly-elytra/', keywords: 'elytra volar planear fuegos artificiales cohetes impulso mending phantom membrane despegar' },
    { name: 'Cómo encontrar y superar las trial chambers en Minecraft', kind: 'guía', url: '/es/guides/how-to-find-trial-chambers/', keywords: 'trial chambers encontrar mapa cartógrafo vault ominosa llave heavy core maza breeze' },
    { name: 'Cómo conseguir Mending en Minecraft', kind: 'guía', url: '/es/guides/how-to-get-mending/', keywords: 'mending encantamiento bibliotecario atril reroll tesoro pantano trade rebalance libro' },
    { name: 'Cómo crear un servidor de Minecraft', kind: 'guía', url: '/es/servidores/make-a-server/', keywords: 'crear servidor paper port forwarding 25565 playit whitelist eula make server' },
    { name: 'Hosting gratis para servidores', kind: 'guía', url: '/es/servidores/free-hosting/', keywords: 'aternos hosting gratis servidor java bedrock free' },
    { name: 'Plugins esenciales para servidores', kind: 'guía', url: '/es/servidores/plugins/', keywords: 'luckperms essentialsx geysermc viaversion coreprotect plugins paper' }
  ];
  return new Response(JSON.stringify(items), { headers: { 'Content-Type': 'application/json' } });
}
